### ISSUE TITLE
TypeScript support

### ISSUE THREAD

**Issue by jpmoura** [arfurlaneto/yup-locale-pt#1]
# Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed
- [x] I'm reporting the issue to the correct repository (for multi-repository projects)

# Expected Behavior

Install the `yup-locale-pt` lib in a TypeScript project and use it in `yup.setLocale` method.

# Current Behavior

Error while compiling because the lack of type definition files (_i.e._ `*.d.ts`)

# Failure Information (for bugs)

```
Could not find a declaration file for module 'yup-locale-pt'. 'node_modules/yup-locale-pt/lib/index.js' implicitly has an 'any' type.
  Try `npm i --save-dev @types/yup-locale-pt` if it exists or add a new declaration (.d.ts) file containing `declare module 'yup-locale-pt';`ts (7016)
```

## Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. Create a TypeScript 
2. Add both Yup and yup-locale-pt dependencies
3. Import and use any yup-locale-pt variant in `Yup.setLocale` method

## Context

* Node Version: 14.5.0 
* Operating System: Windows 10
* TypeScript version: TypeScript 4.1.2
* Yup version: 0.32.8
* yup-locale-pt version: 0.0.5

**Comment by jpmoura** [comment]
I just open the PR #2 adding TypeScript support

**Comment by arfurlaneto** [comment]
Amazing work, much better now. Thanks a lot!

**Comment by arfurlaneto** [comment]
Just published a new version!
