### ISSUE TITLE
Números decimais

### ISSUE THREAD

**Issue by GusMartins499** [arfurlaneto/yup-locale-pt#5]
Olá, primeiro parabéns pela lib.
Minha dúvida é se a validação funciona para número decimais. Por exemplo, eu tenho um campo no meu formulário que deve aceitar somente números positivos, a minha validação está assim: `valor: yup.number().positive().required()`. Quando no meu `input` eu coloco `10.5` funciona, mas quando eu coloco: `10,5` ele não passa na validação. Você sabe alguma maneira de resolver isso ?

**Comment by arfurlaneto** [comment]
Olá!

Este repositório é só da tradução. Para dúvidas do yup você pode dar uma olhada no próprio repositório da lib https://github.com/jquense/yup. Lá tem a documentação de todos os métodos.

Tem um esquema de adicionar novos tipos de validação lá que pode te ajudar.
