### ISSUE TITLE
Not an issue, but how can we use a localized yup for all of our project?

### ISSUE THREAD

**Issue by lucasmaffazioli** [arfurlaneto/yup-locale-pt#6]
More of an implementation question:

I want to create a file, yup.js, that will have the .setLocasel(ptForm) and return yup lozalized, so I can use it normally in my code. This has an objective of not having to rewrite .setLocasel(ptForm) in every file I want to use yup.

Thank you for the package btw!

**Comment by arfurlaneto** [comment]
Hi! It is more an Yup question than about the translation itself, but I can share the way I usually do.

I import yup, set what I want, and then re-export yup. Something like this:

```
import * as Yup from 'yup';
import { pt } from 'yup-locale-pt';

Yup.setLocale(pt);

/* ... set custom methods with 'Yup.addMethod' ... */

export default Yup;
```

Then I always import my re-exported version in my code.

Hope it helps.

**Comment by lucasmaffazioli** [comment]
Thank you very much!
